### ISSUE TITLE
NativeUtility.GetShortPath returns chinese for a network drive

### ISSUE THREAD

**Issue by fifty56** [rdotnet/rdotnet#110]
When I call the setEnvironmentVariables with rHome="\\\\server001xy\folder1\folder2\folder3\folder4\folder5\fold" value, where the length of the string is 58, I get an error message: "Directory '\\\\server001xy\folder1\험º핈º햌º盤滘滙矫⁂蔐" & ChrW(2656) & "ˑ炨˓'' does not exist - cannot set the environment variable R_HOME to that value ". 
I checked the problem and the NativeUtility.GetShortPath returns a bad path containing chinese characters. 

Could you please let me know if this is a bug in my system or on your part?

thanks in advance,
fifty

**Comment by lrasmus** [comment]
Hi @fifty56 - in your code, are you escaping the backslash so that the parameter going into the method for rHome is "\\\\server001xy\\folder1\\folder2\\folder3\\folder4\\folder5\\fold"?

**Comment by fifty56** [comment]
for me it works when I'm using an alias and not the name of the server. So problem solved.
