### ISSUE TITLE
REngine.GetInstance() Null Reference Exception R 3.6.3 RDotNet 1.8.2

### ISSUE THREAD

**Issue by weatherheadio** [rdotnet/rdotnet#121]
I am getting a null reference exception when I call REngine.GetInstance(). I have tried setting the DLL path and Startup Parameters but it has the same result. I am using R 3.6.3 and RDotNet 1.8.2

**Comment by lrasmus** [comment]
I tried installing R 3.6.3, including both 64-bit and 32-bit versions.  I was able to get the following code to run without error:

```
using System;
using RDotNet;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            RDotNet.REngine engine = RDotNet.REngine.GetInstance();
            engine.Evaluate("x <- 1");
            engine.Evaluate("x + 2");
        }
    }
}
```

I have a few questions about your setup that might help troubleshoot:
1. Are you running 64-bit or 32-bit R?  Is your process calling R.NET a 32-bit or 64-bit process?
2. When you installed R 3.6.3, did you install it as an administrator?  Do you know if the option to include the registry keys was left checked during the installation?
3. Is it possible to see a copy of the code you used that's failing?

**Comment by weatherheadio** [comment]
1. I had both the 32-bit and 64-bit R installed.
2. I wasn't admin when it was installed. This was probably the issue. The registry keys option was left checked.
3. I was using REngine.GetInstance() and overloads of that method to give more information (e.g. path to the DLL)
